---

#
# Vagrant Tasks to prepare an appscale vagrant box
#
- name: set vagrant password
  user:
    name: "{{ vagrant_user }}"
    password: "{{ vagrant_password }}"

- name: get vagrant home directory
  shell: >
    getent passwd {{ vagrant_user }} | cut -d: -f6
  register: vagrant_home
  changed_when: False

- name: ensure .ssh directory exists in vagrant home
  file:
    name: "{{ vagrant_home.stdout }}/.ssh"
    state: directory
    owner: "{{ vagrant_user }}"
    group: "{{ vagrant_user }}"
    mode: 0700

- name: set authorized key for vagrant insecure key
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file','files/vagrant_insecure_public_key.pub') }}"

- name: configure sshd allow root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin yes'

- name: configure sshd allow password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'

# when you don't supply the 'replace' key, it will remove the regexp eg: s/ foobar//
- name: remove ttyS0 from grub config
  replace:
    path: /etc/default/grub
    regexp: ' console=ttyS0'

- name: remove ttyS0 from grub cloudimg settings
  replace:
    path: /etc/default/grub.d/50-cloudimg-settings.cfg
    regexp: ' console=ttyS0'

- name: remove unused packages from apt
  apt:
    autoclean: yes

# DD zeros to the filesystem to help when compressing the image
- name: reduce image size
  shell: |
    dd if=/dev/zero of=/EMPTY bs=1M || true
    rm -f /EMPTY
