---

- name: appscale -- common upgrade
  pip:
    name: "file://{{ appscale_home_runtime }}/common"
    extra_args: --upgrade --no-deps
  become: yes
  become_user: root
  tags: appscale_common

- name: appscale -- common
  pip:
    name: "file://{{ appscale_home_runtime }}/common"
  become: yes
  become_user: root
  tags: appscale_common