---

- name: appscale -- adminserver upgrade
  pip:
    name: "file://{{ appscale_home_runtime}}/AdminServer"
    extra_args: --upgrade --no-deps
  become: yes
  become_user: root
  tags: appscale_adminserver

- name: appscale -- adminserver
  pip:
    name: "file://{{ appscale_home_runtime}}/AdminServer"
  become: yes
  become_user: root
  tags: appscale_adminserver