---

- name: appscale -- infrastructure manager upgrade
  pip:
    name: "file://{{ appscale_home_runtime}}/InfrastructureManager"
    extra_args: --upgrade --no-deps
  become: yes
  become_user: root
  tags: appscale_infra

- name: appscale -- infrastructure manager
  pip:
    name: "file://{{ appscale_home_runtime}}/InfrastructureManager"
  become: yes
  become_user: root
  tags: appscale_infra
